---
# tasks file for roles/ansible
- name: Update apt cache (apt-get update)
  apt:
    update_cache: true

- name: Install Ansible
  apt:
    name: ansible
    state: present

- name: Create /etc/ansible directory if it doesn't exist
  file:
    path: /etc/ansible
    state: directory
    mode: '0755'

- name: Create Ansible inventory file from template on EC2
  template:
    src: ../templates/inventory.j2
    dest: /etc/ansible/hosts