---
# tasks file for roles/docker
- name: Update apt cache (apt-get update)
  apt:
    update_cache: true

- name: Install prerequisites for Docker
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: true

- name: Install Docker
  apt:
    name: docker-ce
    state: present


- name: Install improtant packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - build-essential
  - python3-dev 
  - libyaml-dev
  - python3 
  - python3-pip

- name: Ensure python3-pip is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Upgrade pip, setuptools, and wheel
  pip:
    name:
      - pip
      - setuptools
      - wheel
    state: latest
    executable: pip3
    extra_args: --break-system-packages --ignore-installed

- name: installing docker compose
  apt:
    name: docker-compose
    state: present
