version: "3"
services:
  my_app:
    container_name: my_app_container
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: redis
