---
- name: Docker Installation
  hosts: ec2
  become: true  # To run the command as root/superuser
  user: ubuntu  # Since it's an Ubuntu-based EC2 instance
  tasks:
    - name: Update apt cache (apt-get update)
      apt:
        update_cache: true
    
    - name: Install prerequisites for Docker
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker-ce
        state: present